name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master

trigger:
  branches:
    include:
      - master

jobs:
- job: build_job
  displayName: Build Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
    - group: Azure-Static-Web-Apps-ambitious-pond-0848fd303-variable-group
  steps:
    - checkout: self
      submodules: true

    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Ensure the Node.js version matches your app's requirements
      displayName: 'Install Node.js'

    # Install dependencies
    - script: |
        npm install  # Install project dependencies defined in package.json
      displayName: 'Install dependencies'

    # Build Angular app
    - script: |
        npm run build  # Build Angular app (uses the "build" script defined in package.json)
      displayName: 'Build Angular app'

     # Deploy to Azure Static Web App
    - task: AzureStaticWebApp@0
      inputs:
        skip_deploy_on_missing_secrets: true
        app_location: "/"  # Set to the root of your Angular app
        api_location: ""   # Set to "" if you do not have an API
        output_location: "dist/photo-share-app-web"  # Path to the build output (from Angular build)
      displayName: 'Deploy to Azure Static Web App'
