name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

jobs:
- job: build_job
  displayName: Build Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-ambitious-pond-0848fd303-variable-group
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Ensure the Node.js version matches your app's requirements
    displayName: 'Install Node.js'

  - script: |
      npm install  # Install project dependencies defined in package.json
    displayName: 'Install dependencies'

  - script: |
      npm run build  # Build Angular app (uses the "build" script defined in package.json)
    displayName: 'Build Angular app'

  # Optional: If you want to run tests (uncomment if needed)
  # - script: |
  #     npm run test  # Run Angular tests (uses the "test" script defined in package.json)
  #   displayName: 'Run Angular tests'
  
  # Optional: Browsing the output (local preview) – you can add further steps to run tests or any tasks
  # - script: |
  #     echo "Build completed, you can browse the output locally or deploy it."
  #   displayName: 'Browse output (optional)'

